### ISSUE TITLE
'AppLovinSDK/AppLovinSDK.h' file not found

### ISSUE THREAD

**Issue by HessiPard** [quangvo09/react-native-applovin#1]
Hi, Thanks for this great library.
when I want build my project, in xcode it says that:
`'AppLovinSDK/AppLovinSDK.h' file not found`
the error is in RNAppLovinInterstitial.h and RNAppLovinRewarded.h.

note: i also added 
`pod 'AppLovinSDK'`
in my podfile but error exists.

**Comment by HessiPard** [comment]
Just fixed the problem by adding
`s.dependency 'AppLovinSDK'`
in then RNApplovin.podspec.

**Comment by SangJunGameberry** [comment]
> Just fixed the problem by adding
> `s.dependency 'AppLovinSDK'`
> in then RNApplovin.podspec.

HessiPard
I have same this problem
Do you tell me where is RNAApplovin.podspec download file??

**Comment by HessiPard** [comment]
> > Just fixed the problem by adding
> > `s.dependency 'AppLovinSDK'`
> > in then RNApplovin.podspec.
> 
> HessiPard
> I have same this problem
> Do you tell me where is RNAApplovin.podspec download file??

In node_modules/react-native-applovin/ios

**Comment by iRomski** [comment]
Hello! I got this "AppLovinSDK/AppLovinSDK.h' file not found" too but in MAUnityAdManager.h when try to Archive in Xcode... Could you help?

**Comment by tapHero** [comment]
> Hello! I got this "AppLovinSDK/AppLovinSDK.h' file not found" too but in MAUnityAdManager.h when try to Archive in Xcode... Could you help?

@iRomski did You manage to resolve this problem? I can't build on the phone, because of the same warning.
